"use client";

import { Activity, BarChart3, Dumbbell, GraduationCap } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { toast } from "sonner";

import { saveRookieAthleticTest, saveRookieContextSnapshot, saveRookieMarketSnapshot, saveRookieSeason } from "@/app/dashboard/dynasty/rookies/actions";
import { Button } from "@/components/ui/button";
import type { RookiePlayerDetail, RookieSourceSummary } from "@/lib/dynasty/rookie-model/repository";

const now = new Date().toISOString().slice(0, 16);
const optional = (value: string) => value.trim() === "" ? null : Number(value);

export function RookieSnapshotsClient({ player, sources }: { player: RookiePlayerDetail; sources: RookieSourceSummary[] }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [sourceId, setSourceId] = useState("");
  const [season, setSeason] = useState({ games: "", receivingYards: "", receptions: "", rushingYards: "", season: String(player.classYear - 3), targetShare: "" });
  const [athletic, setAthletic] = useState({ eventDate: "", eventType: "combine" as const, fortySeconds: "", ras: "", speedScore: "" });
  const [context, setContext] = useState({ coaching: "", depthChart: "", landingSpot: "", nflTeam: "", observedAt: now, offensiveLine: "", quarterback: "" });
  const [market, setMarket] = useState({ dynastyAdp: "", marketValue: "", observedAt: now, provider: "", rookieAdp: "" });
  function run(action: () => Promise<{ message: string; ok: boolean }>) { if (!sourceId) { toast.error("Choose a source first."); return; } startTransition(async () => { const result = await action(); if (result.ok) { toast.success(result.message); router.refresh(); } else toast.error(result.message); }); }
  const sourceControl = <label className="grid gap-2 text-sm font-semibold text-ink">Evidence source<select value={sourceId} onChange={(event) => setSourceId(event.target.value)} className="h-9 rounded-md border border-ink/15 bg-white px-3 font-normal"><option value="">Choose source</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.label}</option>)}</select></label>;
  return <section className="rounded-lg border border-ink/10 bg-white shadow-soft"><div className="border-b border-ink/10 p-4"><h2 className="font-bold text-ink">Evidence snapshots</h2><p className="mt-1 text-sm text-ink/55">Append dated evidence. Situation and market inputs never change Prospect Score.</p></div><div className="border-b border-ink/10 bg-skyglass/35 p-4">{sourceControl}</div><div className="grid gap-4 p-4 xl:grid-cols-2">
    <article className="rounded-md border border-ink/10 p-4"><h3 className="flex items-center gap-2 font-bold text-ink"><GraduationCap className="h-4 w-4 text-moss" />College season</h3><div className="mt-3 grid grid-cols-2 gap-3">{Object.entries(season).map(([key,value]) => <label key={key} className="grid gap-1 text-xs font-semibold capitalize text-ink/60">{key.replaceAll(/([A-Z])/g," $1")}<input type="number" step="any" value={value} onChange={(event) => setSeason((current) => ({ ...current, [key]: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm text-ink" /></label>)}</div><Button type="button" className="mt-3" disabled={pending} onClick={() => run(() => saveRookieSeason({ games: optional(season.games), playerId: player.id, receivingYards: optional(season.receivingYards), receptions: optional(season.receptions), rushingYards: optional(season.rushingYards), season: Number(season.season), sourceId, targetShare: optional(season.targetShare) }))}>Save season</Button>{player.seasons.length ? <p className="mt-3 text-xs text-ink/50">Latest: {player.seasons[0].playerSeason} - {player.seasons[0].games ?? "-"} games - {player.seasons[0].sourceLabel}</p> : null}</article>
    <article className="rounded-md border border-ink/10 p-4"><h3 className="flex items-center gap-2 font-bold text-ink"><Dumbbell className="h-4 w-4 text-moss" />Athletic test</h3><div className="mt-3 grid grid-cols-2 gap-3"><label className="grid gap-1 text-xs font-semibold text-ink/60">Event<select value={athletic.eventType} onChange={(event) => setAthletic((current) => ({ ...current, eventType: event.target.value as typeof current.eventType }))} className="h-8 rounded border border-ink/15 px-2 text-sm"><option value="combine">Combine</option><option value="pro_day">Pro day</option><option value="other">Other</option></select></label><label className="grid gap-1 text-xs font-semibold text-ink/60">Date<input type="date" value={athletic.eventDate} onChange={(event) => setAthletic((current) => ({ ...current, eventDate: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm" /></label>{([['fortySeconds','Forty seconds'],['speedScore','Speed Score'],['ras','RAS']] as const).map(([key,label]) => <label key={key} className="grid gap-1 text-xs font-semibold text-ink/60">{label}<input type="number" step="any" value={athletic[key]} onChange={(event) => setAthletic((current) => ({ ...current, [key]: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm" /></label>)}</div><Button type="button" className="mt-3" disabled={pending} onClick={() => run(() => saveRookieAthleticTest({ eventDate: athletic.eventDate || null, eventType: athletic.eventType, fortySeconds: optional(athletic.fortySeconds), playerId: player.id, ras: optional(athletic.ras), sourceId, speedScore: optional(athletic.speedScore) }))}>Save test</Button>{player.athleticTests.length ? <p className="mt-3 text-xs text-ink/50">Latest: {player.athleticTests[0].eventType.replace("_"," ")} - RAS {player.athleticTests[0].ras ?? "-"}</p> : null}</article>
    <article className="rounded-md border border-ink/10 p-4"><h3 className="flex items-center gap-2 font-bold text-ink"><Activity className="h-4 w-4 text-moss" />Situation context</h3><div className="mt-3 grid grid-cols-2 gap-3"><label className="grid gap-1 text-xs font-semibold text-ink/60">Observed<input type="datetime-local" value={context.observedAt} onChange={(event) => setContext((current) => ({ ...current, observedAt: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm" /></label><label className="grid gap-1 text-xs font-semibold text-ink/60">NFL team<input value={context.nflTeam} onChange={(event) => setContext((current) => ({ ...current, nflTeam: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm" /></label>{([['landingSpot','Landing spot'],['coaching','Coaching'],['quarterback','Quarterback'],['offensiveLine','Offensive line'],['depthChart','Depth chart']] as const).map(([key,label]) => <label key={key} className="grid gap-1 text-xs font-semibold text-ink/60">{label} (0-100)<input type="number" min="0" max="100" value={context[key]} onChange={(event) => setContext((current) => ({ ...current, [key]: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm" /></label>)}</div><Button type="button" className="mt-3" disabled={pending} onClick={() => run(() => saveRookieContextSnapshot({ coachingScore: optional(context.coaching), depthChartScore: optional(context.depthChart), landingSpotScore: optional(context.landingSpot), nflTeam: context.nflTeam || null, observedAt: context.observedAt, offensiveLineScore: optional(context.offensiveLine), playerId: player.id, quarterbackScore: optional(context.quarterback), sourceId }))}>Save context</Button>{player.contextSnapshots.length ? <p className="mt-3 text-xs text-ink/50">Latest situation: {player.contextSnapshots[0].situationScore?.toFixed(1) ?? "-"}</p> : null}</article>
    <article className="rounded-md border border-ink/10 p-4"><h3 className="flex items-center gap-2 font-bold text-ink"><BarChart3 className="h-4 w-4 text-moss" />Market observation</h3><div className="mt-3 grid grid-cols-2 gap-3"><label className="grid gap-1 text-xs font-semibold text-ink/60">Observed<input type="datetime-local" value={market.observedAt} onChange={(event) => setMarket((current) => ({ ...current, observedAt: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm" /></label><label className="grid gap-1 text-xs font-semibold text-ink/60">Provider<input value={market.provider} onChange={(event) => setMarket((current) => ({ ...current, provider: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm" /></label>{([['rookieAdp','Rookie ADP'],['dynastyAdp','Dynasty ADP'],['marketValue','Market score (0-100)']] as const).map(([key,label]) => <label key={key} className="grid gap-1 text-xs font-semibold text-ink/60">{label}<input type="number" step="any" value={market[key]} onChange={(event) => setMarket((current) => ({ ...current, [key]: event.target.value }))} className="h-8 rounded border border-ink/15 px-2 text-sm" /></label>)}</div><Button type="button" className="mt-3" disabled={pending || !market.provider.trim()} onClick={() => run(() => saveRookieMarketSnapshot({ dynastyAdp: optional(market.dynastyAdp), format: "12-team-superflex", marketValue: optional(market.marketValue), observedAt: market.observedAt, playerId: player.id, provider: market.provider, rookieAdp: optional(market.rookieAdp), sourceId }))}>Save market</Button>{player.marketSnapshots.length ? <p className="mt-3 text-xs text-ink/50">Latest: {player.marketSnapshots[0].provider} - market {player.marketSnapshots[0].marketValue ?? "-"}</p> : null}</article>
  </div></section>;
}
