import { AlertTriangle, ArrowLeft, ShieldCheck } from "lucide-react";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/layout/PageHeader";
import { getRookieBacktestReport } from "@/lib/dynasty/rookie-model/repository";
import { rookieEnginePositions, type RookieEnginePosition } from "@/types/rookie-engine";

export const dynamic = "force-dynamic";

const value = (input: number | null, percent = false) => input === null ? "-" : percent ? `${(input * 100).toFixed(1)}%` : input.toFixed(2);
const interval = (input: [number, number] | null) => input ? `${(input[0] * 100).toFixed(1)}–${(input[1] * 100).toFixed(1)}%` : "-";

export default async function RookieValidationPage({ searchParams }: { searchParams: Promise<{ class?: string; nfl_season?: string; position?: string }> }) {
  const query = await searchParams;
  const parsedClass = Number(query.class);
  const classYear = query.class && Number.isInteger(parsedClass) && parsedClass >= 2020 && parsedClass <= 2026 ? parsedClass : undefined;
  const position = rookieEnginePositions.includes(query.position as RookieEnginePosition) ? query.position as RookieEnginePosition : undefined;
  const nflSeason = query.nfl_season ? Number(query.nfl_season) : undefined;
  const report = await getRookieBacktestReport({ classYear, nflSeason: Number.isFinite(nflSeason) ? nflSeason : undefined, position });
  const hasValidationCohort = report.cohortCount > 0;
  return <div className="space-y-6"><Link href="/dashboard/dynasty/rookies" className="inline-flex items-center gap-2 text-sm font-semibold text-ink/60 hover:text-moss"><ArrowLeft className="h-4 w-4" />Rookie rankings</Link><PageHeader eyebrow="Explainable Rookie Engine" title="Historical validation" description="Retrospective, date-gated validation. One player per target; unpublished or incomplete outcomes never train an earlier class." />
    <section className="rounded-lg border border-violet-200 bg-violet-50 p-5"><h2 className="font-bold text-violet-950">Rolling-origin predictive check</h2><p className="mt-1 text-sm leading-6 text-violet-900/75">Training labels must be available before September 1 of the test draft year. Both models use the same complete-case players, training-only scaling, and fixed L2 regularization (penalty 1). Lower MAE and Brier are better.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-violet-800/70">Evaluated players</p><p className="text-xl font-bold text-violet-950">{report.rollingOrigin.evaluatedCount}</p></div><div><p className="text-xs text-violet-800/70">Prospect PPG MAE</p><p className="text-xl font-bold text-violet-950">{value(report.rollingOrigin.prospectPpgMae)}</p></div><div><p className="text-xs text-violet-800/70">Draft PPG MAE</p><p className="text-xl font-bold text-violet-950">{value(report.rollingOrigin.draftCapitalPpgMae)}</p></div><div><p className="text-xs text-violet-800/70">Combined PPG MAE</p><p className="text-xl font-bold text-violet-950">{value(report.rollingOrigin.combinedPpgMae)}</p></div><div><p className="text-xs text-violet-800/70">Prospect Top-24 Brier</p><p className="text-xl font-bold text-violet-950">{value(report.rollingOrigin.prospectTop24Brier)}</p></div><div><p className="text-xs text-violet-800/70">Draft Top-24 Brier</p><p className="text-xl font-bold text-violet-950">{value(report.rollingOrigin.draftCapitalTop24Brier)}</p></div><div><p className="text-xs text-violet-800/70">Combined Top-24 Brier</p><p className="text-xl font-bold text-violet-950">{value(report.rollingOrigin.combinedTop24Brier)}</p></div></div><p className="mt-3 text-xs text-violet-800/65">Test classes: {report.rollingOrigin.testClasses.length ? report.rollingOrigin.testClasses.join(", ") : "none yet"}</p></section>
    {report.familyAblations.length ? <section className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Feature-family ablation</h2><p className="mt-1 text-sm text-ink/55">Each row uses the same complete-case players for its family, draft-only baseline, and combined model. Lower is better.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-ink/10 text-xs uppercase tracking-wide text-ink/45"><th className="py-2 pr-4">Family</th><th className="px-3 py-2">n</th><th className="px-3 py-2">Family MAE</th><th className="px-3 py-2">Draft MAE</th><th className="px-3 py-2">Combined MAE</th><th className="px-3 py-2">Family Brier</th><th className="px-3 py-2">Draft Brier</th><th className="pl-3 py-2">Combined Brier</th></tr></thead><tbody>{report.familyAblations.map((row) => <tr key={row.familyKey} className="border-b border-ink/5 last:border-0"><td className="py-3 pr-4 font-semibold capitalize">{row.familyKey.replaceAll("_", " ")}</td><td className="px-3 py-3">{row.evaluatedCount}</td><td className="px-3 py-3">{value(row.familyPpgMae)}</td><td className="px-3 py-3">{value(row.draftCapitalPpgMae)}</td><td className="px-3 py-3 font-semibold text-moss">{value(row.combinedPpgMae)}</td><td className="px-3 py-3">{value(row.familyTop24Brier)}</td><td className="px-3 py-3">{value(row.draftCapitalTop24Brier)}</td><td className="pl-3 py-3 font-semibold text-moss">{value(row.combinedTop24Brier)}</td></tr>)}</tbody></table></div></section> : null}
    {report.metricAblations.length ? <section className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Metric-level predictive check</h2><p className="mt-1 text-sm text-ink/55">Historical score components are normalized; extra metrics such as career YPRR retain raw units. Both are standardized using training data only. These exploratory tests are not untouched holdouts.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-ink/10 text-xs uppercase tracking-wide text-ink/45"><th className="py-2 pr-4">Metric</th><th className="px-3 py-2">n</th><th className="px-3 py-2">Metric MAE</th><th className="px-3 py-2">Draft MAE</th><th className="px-3 py-2">Combined MAE</th><th className="px-3 py-2">Metric Brier</th><th className="px-3 py-2">Draft Brier</th><th className="pl-3 py-2">Combined Brier</th></tr></thead><tbody>{report.metricAblations.map((row) => <tr key={row.metricKey} className="border-b border-ink/5 last:border-0"><td className="py-3 pr-4 font-semibold capitalize">{row.metricKey.replaceAll("_", " ")}</td><td className="px-3 py-3">{row.evaluatedCount}</td><td className="px-3 py-3">{value(row.metricPpgMae)}</td><td className="px-3 py-3">{value(row.draftCapitalPpgMae)}</td><td className="px-3 py-3 font-semibold text-moss">{value(row.combinedPpgMae)}</td><td className="px-3 py-3">{value(row.metricTop24Brier)}</td><td className="px-3 py-3">{value(row.draftCapitalTop24Brier)}</td><td className="pl-3 py-3 font-semibold text-moss">{value(row.combinedTop24Brier)}</td></tr>)}</tbody></table></div></section> : null}
    {report.historicalLeaders.length ? <section className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Top five from the last three historical classes</h2><p className="mt-1 text-sm text-ink/55">Stored scouting scores, not fitted predictions. Default outcomes are first-three-season peak statistical-appearance PPR PPG and best finish; a selected NFL season overrides that window.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-ink/10 text-xs uppercase tracking-wide text-ink/45"><th className="py-2 pr-3">Class</th><th className="px-3 py-2">Rank</th><th className="px-3 py-2">Player</th><th className="px-3 py-2">Overall</th><th className="px-3 py-2">Prospect</th><th className="px-3 py-2">NFL PPG</th><th className="pl-3 py-2">Pos. finish</th></tr></thead><tbody>{report.historicalLeaders.map((row, index, rows) => { const classRank = rows.slice(0, index).filter((candidate) => candidate.classYear === row.classYear).length + 1; return <tr key={`${row.classYear}-${row.playerId}`} className="border-b border-ink/5 last:border-0"><td className="py-3 pr-3 font-semibold">{row.classYear}</td><td className="px-3 py-3">{classRank}</td><td className="px-3 py-3"><Link href={`/dashboard/dynasty/rookies/${row.playerId}`} className="font-semibold text-moss hover:underline">{row.playerName}</Link></td><td className="px-3 py-3 font-semibold">{value(row.overallScore)}</td><td className="px-3 py-3">{value(row.prospectScore)}</td><td className="px-3 py-3">{value(row.fantasyPpg)}</td><td className="pl-3 py-3">{row.positionFinish ?? "-"}</td></tr>; })}</tbody></table></div></section> : null}
    {report.outcomeAudit ? <section className="rounded-lg border border-amber-300 bg-amber-50 p-5 text-sm text-amber-950"><h2 className="font-bold">Outcome coverage audit</h2><p className="mt-2">{report.outcomeAudit.mode}. Imported seasons: {report.outcomeAudit.seasons.join(", ") || "none"}.</p><p className="mt-2">Matured players: {report.outcomeAudit.maturedPlayers}; incomplete class windows: {report.outcomeAudit.immaturePlayers}; no outcome rows: {report.outcomeAudit.missingEntireWindow}; partially missing seasons: {report.outcomeAudit.missingSomeSeasons}.</p><p className="mt-2">Missing seasons are unknown, not zeroes. Complete-case results can exclude failed prospects and have survivorship bias until those gaps are verified. PPG uses statistical appearances, not roster games. Historical model versions and source revisions also limit interpretation. Do not promote weights based on these exploratory results.</p></section> : null}
    {!hasValidationCohort ? <p className="text-sm text-amber-900">No complete historical targets are available for this selection. The scouting ranking is not empirically validated.</p> : null}
    <form className="grid gap-3 rounded-lg border border-ink/10 bg-white p-4 shadow-soft sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-end"><label className="grid gap-2 text-sm font-semibold text-ink">Draft class<select name="class" defaultValue={query.class ?? ""} className="h-9 rounded-md border border-ink/15 px-3 font-normal"><option value="">All classes</option>{[2020, 2021, 2022, 2023, 2024, 2025, 2026].map((year) => <option key={year} value={year}>{year}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold text-ink">Position<select name="position" defaultValue={query.position ?? ""} className="h-9 rounded-md border border-ink/15 px-3 font-normal"><option value="">All positions</option>{rookieEnginePositions.map((candidate) => <option key={candidate} value={candidate}>{candidate}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold text-ink">NFL outcome season<input name="nfl_season" type="number" min="2020" max="2035" defaultValue={query.nfl_season ?? ""} className="h-9 rounded-md border border-ink/15 px-3 font-normal" /></label><Button type="submit">Run report</Button></form>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg border border-ink/10 bg-white p-4 shadow-soft"><p className="text-sm text-ink/50">Eligible cohort</p><p className="mt-2 text-3xl font-bold text-ink">{report.cohortCount}</p></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><p className="text-sm text-amber-800">Leakage exclusions</p><p className="mt-2 text-3xl font-bold text-amber-900">{report.excludedForLeakage}</p></div><div className="rounded-lg border border-ink/10 bg-white p-4 shadow-soft"><p className="text-sm text-ink/50">Top-12 finish rate</p><p className="mt-2 text-3xl font-bold text-moss">{value(report.metrics.top12Rate, true)}</p></div><div className="rounded-lg border border-ink/10 bg-white p-4 shadow-soft"><p className="text-sm text-ink/50">Top-24 finish rate</p><p className="mt-2 text-3xl font-bold text-moss">{value(report.metrics.top24Rate, true)}</p></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Multiple outcomes</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-ink/50">Average target PPG</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.metrics.averageFantasyPpg)}</dd></div><div><dt className="text-ink/50">Average games in target window</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.metrics.averageGames)}</dd></div><div><dt className="text-ink/50">Average peak dynasty value</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.metrics.averagePeakDynastyValue)}</dd></div><div><dt className="text-ink/50">Missing-outcome exclusions</dt><dd className="mt-1 text-xl font-bold text-ink">{report.excludedWithoutOutcome}</dd></div><div><dt className="text-ink/50">Top-12 95% interval</dt><dd className="mt-1 font-bold text-ink">{interval(report.metrics.top12Interval)}</dd></div><div><dt className="text-ink/50">Top-24 95% interval</dt><dd className="mt-1 font-bold text-ink">{interval(report.metrics.top24Interval)}</dd></div></dl></article><article className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Rank correlation to fantasy PPG</h2><p className="mt-1 text-sm text-ink/50">Spearman correlation; requires at least three paired observations.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-ink/50">Prospect</dt><dd className="mt-1 text-xl font-bold text-moss">{value(report.rankCorrelations.prospectToPpg)}</dd></div><div><dt className="text-ink/50">Draft capital</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.rankCorrelations.draftCapitalToPpg)}</dd></div><div><dt className="text-ink/50">Market</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.rankCorrelations.marketToPpg)}</dd></div><div><dt className="text-ink/50">Consensus rank</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.rankCorrelations.consensusToPpg)}</dd></div></dl></article></section>
    <section className="grid gap-4 lg:grid-cols-[0.65fr_1.35fr]"><article className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Classification check</h2><p className="mt-1 text-sm text-ink/50">Rule: Prospect Score ≥ {report.classification.scoreThreshold} predicts {report.classification.target}.</p><dl className="mt-4 grid grid-cols-2 gap-3"><div><dt className="text-sm text-ink/50">Precision</dt><dd className="mt-1 text-2xl font-bold text-moss">{value(report.classification.precision, true)}</dd></div><div><dt className="text-sm text-ink/50">Recall</dt><dd className="mt-1 text-2xl font-bold text-moss">{value(report.classification.recall, true)}</dd></div></dl></article><article className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Observed outcome buckets</h2><p className="mt-1 text-sm text-ink/50">Observed top-24 rates by score range; these are not player probabilities.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{report.calibrationBuckets.map((bucket) => <div key={bucket.label} className="rounded-md border border-ink/10 bg-mist/40 p-3"><p className="text-xs font-bold text-ink/50">Score {bucket.label}</p><p className="mt-2 text-lg font-bold text-ink">{value(bucket.observedTop24Rate, true)}</p><p className="text-xs text-ink/45">n={bucket.count}</p></div>)}</div></article></section>
    <section className="rounded-lg border border-sky-200 bg-sky-50 p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-sky-800" /><div><h2 className="font-bold text-sky-950">Rolling-origin protection</h2><p className="mt-1 text-sm leading-6 text-sky-900/75">Scores and inputs must be dated by September 1 of the draft year. A three-year outcome is available no earlier than April 1 following its final NFL season. Retrospective source revisions and model selection mean this is not a prospective validation claim.</p></div></div>{report.cohortCount < 20 ? <div className="mt-4 flex gap-2 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle className="h-4 w-4 shrink-0" />Small cohorts are unstable. Do not interpret these results as calibrated probabilities.</div> : null}</section>
  </div>;
}
