import { AlertTriangle, ArrowLeft, ShieldCheck } from "lucide-react";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/layout/PageHeader";
import { getRookieBacktestReport } from "@/lib/dynasty/rookie-model/repository";

export const dynamic = "force-dynamic";

const value = (input: number | null, percent = false) => input === null ? "-" : percent ? `${(input * 100).toFixed(1)}%` : input.toFixed(2);
const interval = (input: [number, number] | null) => input ? `${(input[0] * 100).toFixed(1)}–${(input[1] * 100).toFixed(1)}%` : "-";

export default async function RookieValidationPage({ searchParams }: { searchParams: Promise<{ class?: string; nfl_season?: string; position?: string }> }) {
  const query = await searchParams;
  const classYear = query.class === "2025" || query.class === "2026" ? Number(query.class) : undefined;
  const position = query.position === "RB" || query.position === "WR" ? query.position : undefined;
  const nflSeason = query.nfl_season ? Number(query.nfl_season) : undefined;
  const report = await getRookieBacktestReport({ classYear, nflSeason: Number.isFinite(nflSeason) ? nflSeason : undefined, position });
  return <div className="space-y-6"><Link href="/dashboard/dynasty/rookies" className="inline-flex items-center gap-2 text-sm font-semibold text-ink/60 hover:text-moss"><ArrowLeft className="h-4 w-4" />Rookie rankings</Link><PageHeader eyebrow="Explainable Rookie Engine" title="Historical validation" description="Leakage-safe outcome reporting across multiple definitions. Scores remain rankings, not hit probabilities." />
    <form className="grid gap-3 rounded-lg border border-ink/10 bg-white p-4 shadow-soft sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-end"><label className="grid gap-2 text-sm font-semibold text-ink">Draft class<select name="class" defaultValue={query.class ?? ""} className="h-9 rounded-md border border-ink/15 px-3 font-normal"><option value="">All classes</option><option value="2025">2025</option><option value="2026">2026</option></select></label><label className="grid gap-2 text-sm font-semibold text-ink">Position<select name="position" defaultValue={query.position ?? ""} className="h-9 rounded-md border border-ink/15 px-3 font-normal"><option value="">RB and WR</option><option value="RB">RB</option><option value="WR">WR</option></select></label><label className="grid gap-2 text-sm font-semibold text-ink">NFL outcome season<input name="nfl_season" type="number" min="2025" max="2035" defaultValue={query.nfl_season ?? ""} className="h-9 rounded-md border border-ink/15 px-3 font-normal" /></label><Button type="submit">Run report</Button></form>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg border border-ink/10 bg-white p-4 shadow-soft"><p className="text-sm text-ink/50">Eligible cohort</p><p className="mt-2 text-3xl font-bold text-ink">{report.cohortCount}</p></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><p className="text-sm text-amber-800">Leakage exclusions</p><p className="mt-2 text-3xl font-bold text-amber-900">{report.excludedForLeakage}</p></div><div className="rounded-lg border border-ink/10 bg-white p-4 shadow-soft"><p className="text-sm text-ink/50">Top-12 finish rate</p><p className="mt-2 text-3xl font-bold text-moss">{value(report.metrics.top12Rate, true)}</p></div><div className="rounded-lg border border-ink/10 bg-white p-4 shadow-soft"><p className="text-sm text-ink/50">Top-24 finish rate</p><p className="mt-2 text-3xl font-bold text-moss">{value(report.metrics.top24Rate, true)}</p></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Multiple outcomes</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-ink/50">Average fantasy PPG</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.metrics.averageFantasyPpg)}</dd></div><div><dt className="text-ink/50">Average games</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.metrics.averageGames)}</dd></div><div><dt className="text-ink/50">Average peak dynasty value</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.metrics.averagePeakDynastyValue)}</dd></div><div><dt className="text-ink/50">Missing-outcome exclusions</dt><dd className="mt-1 text-xl font-bold text-ink">{report.excludedWithoutOutcome}</dd></div><div><dt className="text-ink/50">Top-12 95% interval</dt><dd className="mt-1 font-bold text-ink">{interval(report.metrics.top12Interval)}</dd></div><div><dt className="text-ink/50">Top-24 95% interval</dt><dd className="mt-1 font-bold text-ink">{interval(report.metrics.top24Interval)}</dd></div></dl></article><article className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Rank correlation to fantasy PPG</h2><p className="mt-1 text-sm text-ink/50">Spearman correlation; requires at least three paired observations.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-ink/50">Prospect</dt><dd className="mt-1 text-xl font-bold text-moss">{value(report.rankCorrelations.prospectToPpg)}</dd></div><div><dt className="text-ink/50">Draft capital</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.rankCorrelations.draftCapitalToPpg)}</dd></div><div><dt className="text-ink/50">Market</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.rankCorrelations.marketToPpg)}</dd></div><div><dt className="text-ink/50">Consensus rank</dt><dd className="mt-1 text-xl font-bold text-ink">{value(report.rankCorrelations.consensusToPpg)}</dd></div></dl></article></section>
    <section className="grid gap-4 lg:grid-cols-[0.65fr_1.35fr]"><article className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Classification check</h2><p className="mt-1 text-sm text-ink/50">Rule: Prospect Score ≥ {report.classification.scoreThreshold} predicts {report.classification.target}.</p><dl className="mt-4 grid grid-cols-2 gap-3"><div><dt className="text-sm text-ink/50">Precision</dt><dd className="mt-1 text-2xl font-bold text-moss">{value(report.classification.precision, true)}</dd></div><div><dt className="text-sm text-ink/50">Recall</dt><dd className="mt-1 text-2xl font-bold text-moss">{value(report.classification.recall, true)}</dd></div></dl></article><article className="rounded-lg border border-ink/10 bg-white p-5 shadow-soft"><h2 className="font-bold text-ink">Observed outcome buckets</h2><p className="mt-1 text-sm text-ink/50">Observed top-24 rates by score range; these are not player probabilities.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{report.calibrationBuckets.map((bucket) => <div key={bucket.label} className="rounded-md border border-ink/10 bg-mist/40 p-3"><p className="text-xs font-bold text-ink/50">Score {bucket.label}</p><p className="mt-2 text-lg font-bold text-ink">{value(bucket.observedTop24Rate, true)}</p><p className="text-xs text-ink/45">n={bucket.count}</p></div>)}</div></article></section>
    <section className="rounded-lg border border-sky-200 bg-sky-50 p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-sky-800" /><div><h2 className="font-bold text-sky-950">Rolling-origin protection</h2><p className="mt-1 text-sm leading-6 text-sky-900/75">A draft class can only use a score dated on or before September 1 of its draft year. Later runs are excluded and counted above. Outcome data never enters scoring inputs.</p></div></div>{report.cohortCount < 20 ? <div className="mt-4 flex gap-2 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle className="h-4 w-4 shrink-0" />Small cohorts are unstable. Do not interpret these results as calibrated probabilities.</div> : null}</section>
  </div>;
}
