export type CareerTrack = "Logistics" | "Tech Sales" | "Development Program";

export type WatchedCompany = {
  careersUrl: string;
  company: string;
  locationNote: string;
  tracks: CareerTrack[];
  automated: boolean;
};

export const careerTracks: CareerTrack[] = ["Logistics", "Tech Sales", "Development Program"];

// The scout still applies the Atlanta/Georgia location gate to every opening.
export const watchedCompanies: WatchedCompany[] = [
  { company: "UPS", tracks: ["Logistics", "Development Program"], careersUrl: "https://www.jobs-ups.com/", locationNote: "Atlanta headquarters and Georgia operations", automated: false },
  { company: "Delta Air Lines", tracks: ["Logistics", "Development Program"], careersUrl: "https://delta.avature.net/careers", locationNote: "Atlanta headquarters", automated: false },
  { company: "Norfolk Southern", tracks: ["Logistics", "Development Program"], careersUrl: "https://jobs.nscorp.com/", locationNote: "Atlanta headquarters", automated: false },
  { company: "CSX", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.csx.com/", locationNote: "Georgia rail operations", automated: false },
  { company: "FedEx", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.fedex.com/", locationNote: "Metro Atlanta operations", automated: false },
  { company: "DHL Supply Chain", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.dhl.com/", locationNote: "Georgia distribution network", automated: false },
  { company: "GXO Logistics", tracks: ["Logistics"], careersUrl: "https://jobs.gxo.com/", locationNote: "Georgia operations", automated: false },
  { company: "XPO", tracks: ["Logistics"], careersUrl: "https://jobs.xpo.com/", locationNote: "Metro Atlanta terminals", automated: false },
  { company: "Ryder", tracks: ["Logistics", "Development Program"], careersUrl: "https://ryder.com/careers", locationNote: "Metro Atlanta operations", automated: false },
  { company: "Penske", tracks: ["Logistics", "Development Program"], careersUrl: "https://penske.jobs/", locationNote: "Sales and operations trainee roles", automated: false },
  { company: "Maersk", tracks: ["Logistics"], careersUrl: "https://www.maersk.com/careers/vacancies", locationNote: "Atlanta and Savannah", automated: false },
  { company: "Flexport", tracks: ["Logistics", "Tech Sales"], careersUrl: "https://www.flexport.com/careers/", locationNote: "Atlanta office", automated: true },
  { company: "C.H. Robinson", tracks: ["Logistics", "Tech Sales"], careersUrl: "https://jobs.chrobinson.com/", locationNote: "Atlanta office", automated: false },
  { company: "J.B. Hunt", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.jbhunt.com/", locationNote: "Georgia operations", automated: false },
  { company: "Schneider", tracks: ["Logistics"], careersUrl: "https://schneiderjobs.com/", locationNote: "Georgia operations", automated: false },
  { company: "Kuehne+Nagel", tracks: ["Logistics"], careersUrl: "https://jobs.kuehne-nagel.com/", locationNote: "Atlanta office", automated: false },
  { company: "DSV", tracks: ["Logistics"], careersUrl: "https://www.dsv.com/en/careers/job-openings", locationNote: "Atlanta office", automated: false },
  { company: "CEVA Logistics", tracks: ["Logistics"], careersUrl: "https://www.cevalogistics.com/en/careers", locationNote: "Georgia operations", automated: false },
  { company: "DB Schenker", tracks: ["Logistics"], careersUrl: "https://www.dbschenker.com/global/careers/jobs-portal", locationNote: "Atlanta office", automated: false },
  { company: "Expeditors", tracks: ["Logistics"], careersUrl: "https://www.expeditors.com/careers", locationNote: "Atlanta office", automated: false },
  { company: "NFI Industries", tracks: ["Logistics"], careersUrl: "https://careers.nfiindustries.com/", locationNote: "Georgia operations", automated: false },
  { company: "Americold", tracks: ["Logistics"], careersUrl: "https://careers.americold.com/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Lineage", tracks: ["Logistics"], careersUrl: "https://onelineage.com/careers", locationNote: "Georgia cold-chain operations", automated: false },
  { company: "Saddle Creek Logistics", tracks: ["Logistics"], careersUrl: "https://www.sclogistics.com/careers/", locationNote: "Metro Atlanta operations", automated: false },
  { company: "Total Quality Logistics", tracks: ["Logistics", "Tech Sales"], careersUrl: "https://careers.tql.com/", locationNote: "Atlanta office", automated: false },
  { company: "Echo Global Logistics", tracks: ["Logistics", "Tech Sales"], careersUrl: "https://www.echo.com/careers", locationNote: "Atlanta office", automated: false },
  { company: "Nolan Transportation Group", tracks: ["Logistics", "Tech Sales"], careersUrl: "https://ntgfreight.com/careers/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Uber Freight", tracks: ["Logistics", "Tech Sales"], careersUrl: "https://www.uberfreight.com/careers/", locationNote: "Watch for Atlanta openings", automated: false },
  { company: "Roadie", tracks: ["Logistics", "Tech Sales"], careersUrl: "https://www.roadie.com/careers", locationNote: "Atlanta headquarters", automated: true },
  { company: "Stord", tracks: ["Logistics", "Tech Sales"], careersUrl: "https://www.stord.com/careers", locationNote: "Atlanta headquarters", automated: false },
  { company: "Manhattan Associates", tracks: ["Logistics", "Tech Sales", "Development Program"], careersUrl: "https://www.manh.com/about-us/careers", locationNote: "Atlanta headquarters", automated: false },
  { company: "The Home Depot", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.homedepot.com/job-search-results/", locationNote: "Atlanta headquarters and supply chain", automated: false },
  { company: "The Coca-Cola Company", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.coca-colacompany.com/", locationNote: "Atlanta headquarters", automated: true },
  { company: "Georgia-Pacific", tracks: ["Logistics", "Development Program"], careersUrl: "https://jobs.kochcareers.com/georgia-pacific", locationNote: "Atlanta headquarters", automated: false },
  { company: "Genuine Parts Company", tracks: ["Logistics", "Development Program"], careersUrl: "https://jobs.genpt.com/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Chick-fil-A", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.chick-fil-a.com/", locationNote: "Atlanta headquarters and distribution", automated: false },
  { company: "RaceTrac", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.racetrac.com/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Newell Brands", tracks: ["Logistics", "Development Program"], careersUrl: "https://jobs.newellbrands.com/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Carter's", tracks: ["Logistics"], careersUrl: "https://careers.carters.com/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Floor & Decor", tracks: ["Logistics"], careersUrl: "https://careers.flooranddecor.com/", locationNote: "Atlanta headquarters", automated: false },
  { company: "HD Supply", tracks: ["Logistics"], careersUrl: "https://hdsupply.jobs/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Mohawk Industries", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.mohawkind.com/", locationNote: "North Georgia headquarters", automated: false },
  { company: "Gulfstream Aerospace", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.gulfstream.com/", locationNote: "Savannah", automated: false },
  { company: "Kia Georgia", tracks: ["Logistics", "Development Program"], careersUrl: "https://www.kiajobsingeorgia.com/", locationNote: "West Point", automated: false },
  { company: "Hyundai Motor Group Metaplant America", tracks: ["Logistics", "Development Program"], careersUrl: "https://careers.hmgma.com/", locationNote: "Savannah area", automated: false },
  { company: "Porsche Cars North America", tracks: ["Logistics", "Development Program"], careersUrl: "https://www.porsche.com/usa/aboutporsche/jobs/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Mercedes-Benz USA", tracks: ["Logistics", "Development Program"], careersUrl: "https://group.mercedes-benz.com/careers/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Salesforce", tracks: ["Tech Sales"], careersUrl: "https://careers.salesforce.com/en/jobs/", locationNote: "Atlanta BDR organization", automated: false },
  { company: "OneTrust", tracks: ["Tech Sales"], careersUrl: "https://www.onetrust.com/careers/", locationNote: "Atlanta headquarters", automated: true },
  { company: "Salesloft", tracks: ["Tech Sales"], careersUrl: "https://www.salesloft.com/company/careers", locationNote: "Atlanta headquarters", automated: true },
  { company: "ServiceNow", tracks: ["Tech Sales"], careersUrl: "https://careers.servicenow.com/", locationNote: "Atlanta office", automated: false },
  { company: "Workday", tracks: ["Tech Sales"], careersUrl: "https://workday.wd5.myworkdayjobs.com/Workday", locationNote: "Atlanta office", automated: false },
  { company: "Oracle", tracks: ["Tech Sales"], careersUrl: "https://careers.oracle.com/", locationNote: "Atlanta sales roles", automated: false },
  { company: "SAP", tracks: ["Tech Sales", "Development Program"], careersUrl: "https://jobs.sap.com/", locationNote: "Atlanta sales roles", automated: false },
  { company: "Microsoft", tracks: ["Tech Sales"], careersUrl: "https://jobs.careers.microsoft.com/", locationNote: "Atlanta office", automated: false },
  { company: "Amazon Web Services", tracks: ["Tech Sales"], careersUrl: "https://www.amazon.jobs/", locationNote: "Atlanta sales roles", automated: false },
  { company: "Google", tracks: ["Tech Sales"], careersUrl: "https://www.google.com/about/careers/applications/jobs/results/", locationNote: "Atlanta office", automated: false },
  { company: "NCR Voyix", tracks: ["Tech Sales", "Logistics"], careersUrl: "https://www.ncrvoyix.com/company/careers", locationNote: "Atlanta headquarters", automated: false },
  { company: "Fiserv", tracks: ["Tech Sales"], careersUrl: "https://www.careers.fiserv.com/", locationNote: "Alpharetta campus", automated: false },
  { company: "Samsara", tracks: ["Tech Sales", "Logistics"], careersUrl: "https://www.samsara.com/company/careers", locationNote: "Watch for Atlanta roles", automated: false },
  { company: "Motive", tracks: ["Tech Sales", "Logistics"], careersUrl: "https://gomotive.com/company/careers/", locationNote: "Watch for Georgia roles", automated: false },
  { company: "OnPay", tracks: ["Tech Sales"], careersUrl: "https://careers.onpay.com/", locationNote: "Atlanta headquarters", automated: false },
  { company: "Rev.io", tracks: ["Tech Sales"], careersUrl: "https://jobs.rev.io/", locationNote: "Atlanta headquarters", automated: false },
  { company: "sunday", tracks: ["Tech Sales"], careersUrl: "https://careers.sundayapp.com/", locationNote: "Atlanta office", automated: false },
  { company: "TRACTIAN", tracks: ["Tech Sales"], careersUrl: "https://careers.tractian.com/", locationNote: "Atlanta sales team", automated: false },
  { company: "Speedchain", tracks: ["Tech Sales"], careersUrl: "https://www.speedchain.com/careers", locationNote: "Atlanta headquarters", automated: false },
  { company: "GE Vernova", tracks: ["Development Program", "Logistics"], careersUrl: "https://careers.gevernova.com/operations-management-development-program", locationNote: "OMDP; surface Georgia placements only", automated: false },
  { company: "Eaton", tracks: ["Development Program", "Logistics"], careersUrl: "https://www.eaton.com/us/en-us/company/careers/early-talent.html", locationNote: "Operations Management LDP", automated: false },
  { company: "Siemens", tracks: ["Development Program", "Logistics"], careersUrl: "https://www.siemens.com/us/en/company/jobs/search-careers.html", locationNote: "Early-career operations programs", automated: false },
  { company: "Honeywell", tracks: ["Development Program", "Logistics"], careersUrl: "https://careers.honeywell.com/", locationNote: "Atlanta headquarters presence", automated: false },
  { company: "RTX", tracks: ["Development Program", "Logistics"], careersUrl: "https://careers.rtx.com/", locationNote: "Operations and supply-chain programs", automated: false },
  { company: "Lockheed Martin", tracks: ["Development Program", "Logistics"], careersUrl: "https://www.lockheedmartinjobs.com/", locationNote: "Marietta", automated: false },
  { company: "Boeing", tracks: ["Development Program", "Logistics"], careersUrl: "https://jobs.boeing.com/", locationNote: "Supply-chain early career", automated: false },
  { company: "PepsiCo", tracks: ["Development Program", "Logistics"], careersUrl: "https://www.pepsicojobs.com/", locationNote: "Georgia operations", automated: false },
  { company: "Grainger", tracks: ["Development Program", "Logistics"], careersUrl: "https://jobs.grainger.com/", locationNote: "Supply-chain development roles", automated: false },
  { company: "Caterpillar", tracks: ["Development Program", "Logistics"], careersUrl: "https://careers.caterpillar.com/", locationNote: "Georgia facilities", automated: false },
];

